spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=utf-8
    username: root
    password: guddqs
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 9988
mybatis:
  type-aliases-package: com.guddqs
  mapper-locations: classpath:mybatis-mapper/*.xml
logging:
  config: classpath:logback.xml